name: Run code format checks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  run-pre-commit-checks:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.70.1
          frozen: true

      - name: Run tests
        run: pixi run -e linters linters
